### PR TITLE
Release 10-2-3: Initial Notes

### PR DESCRIPTION
**Pull request by vibhus**
Initial notes for v10.2.3

### CODE REVIEW

**Comment by prasanth-reddy-wavemaker-com** [comment]
@swethakundaram shouldn't we have waited until we actually released 10.2.3?

**Comment by swethakundaram-wm** [comment]
Merged to the `release/WMO10.2.3_Release` branch. After the actual release, we can publish it to the master.

**Comment by prasanth-reddy-wavemaker-com** [comment]
When making the release notes, lets also update the API version in the documentation. See this change
https://github.com/wavemaker/docs/pull/65/files

@rnaresh @swethakundaram @vibhus

**Comment by swethakundaram-wm** [comment]
If we know the build number for sure, we can add that to the to-do in the release branch itself.

**Comment by prasanth-reddy-wavemaker-com** [comment]
Why is the build number part of the url, We should remove it @wmrnaresh @vibhus

**Comment by vibhus** [comment]
The API docs are generated as part of the ng-runtime repo. It is also deployed along with the studio which is versioned per build. Hence the build number in docs links.

**Comment by prasanth-reddy-wavemaker-com** [comment]
lets remove the build number and keep the major.minor.minor versions only. 10.2.3 @vibhus

**Comment by vibhus** [comment]
Will need to check with ops on this.

**Pull request merged**
