### PR TITLE
Scheme linking

### PR DESCRIPTION
**Pull request by shilwantkumar**

### CODE REVIEW

**Comment by prasanth-reddy-wavemaker-com** [comment]
@shilwantkumar can you build this locally and see why the checks are failing?

**Comment by vivek-dhayalan** [comment]
> @shilwantkumar can you build this locally and see why the checks are failing?

@prasanth-reddy-wavemaker-com I have fixed the issue! the build is running. Apparently, the issues seems to because of the previous changes. By merging this change I assume it will fix the issue in the main branch as well.

**Comment by prasanth-reddy-wavemaker-com** [comment]
@shilwantkumar @vivek-dhayalan I have requested some changes to be made to this PR. please take a look at my comment above.

**Review by prasanth-reddy-wavemaker-com — CHANGES_REQUESTED** [review]
Please also change the this page's url to deep linking from scheme linking

**Review by prasanth-reddy-wavemaker-com — CHANGES_REQUESTED** [review]
deepling wrong spelling

**Review by prasanth-reddy-wavemaker-com — CHANGES_REQUESTED** [review]
Starting sentence in the Universal Linking (ios) seems to start abruptly without any context. please check that.

**Comment by prasanth-reddy-wavemaker-com** [comment]
@vivek-dhayalan I am request some more changes, please take a look. After those are addressed, I can merge this. Thank you.

**Review by prasanth-reddy-wavemaker-com — APPROVED** [review]

**Comment by prasanth-reddy-wavemaker-com** [comment]
LGTM @vivek-dhayalan 
Thanks for the patience and the content looks much better now. 
Can you please check the failing checks? After the checks pass i will merge this in.

**Pull request merged**
