### PR TITLE
Algolia DocSearch integrated #46

### PR DESCRIPTION
**Pull request by sharath0033**
Algolia DocSearch integrated with default styles provided by the service.

### CODE REVIEW

**Comment by rnaresh** [comment]
https://github.com/facebook/Docusaurus/issues/872

@prasanth-reddy-wavemaker-com Customising Header is not possible at the moment. It will be enabled in v2

**Comment by prasanth-reddy-wavemaker-com** [comment]
Can we write js code in header.js to make header a dropdown in mobile only? @rnaresh

**Comment by prasanth-reddy-wavemaker-com** [comment]
@rnaresh needs to hash the css files so that browser content is flushed.
Otherwise the customers have to force refresh their browsers to see the search functionality.

**Comment by prasanth-reddy-wavemaker-com** [comment]
@lovin26 in mobile the docs and searchbar should have padding. check this screenshot
image

**Comment by prasanth-reddy-wavemaker-com** [comment]
@lovin26 i made some padding change to fix the issue i screenshoted in my comment above.

**Comment by lovin26** [comment]
Are the changes merged into master?

> @lovin26 i made some padding change to fix the issue i screenshoted in my comment above.

**Comment by mateusmarquezini** [comment]
> [facebook/docusaurus#872](https://github.com/facebook/docusaurus/issues/872)
> 
> @prasanth-reddy-wavemaker-com Customising Header is not possible at the moment. It will be enabled in v2

@rnaresh the current Docusaurus v2.0.0-alpha is already possible to customize the Header component or only in the future?

**Pull request merged**
