### PR TITLE
Themes builder and creating manual theme

### PR DESCRIPTION
**Pull request by swethakundaram**

### CODE REVIEW

**Comment by prasanth-reddy-wavemaker-com** [comment]
Can you include screenshots of the changes? @swethakundaram

**Comment by swethakundaram** [comment]
1. Added a separate doc for [Theme Builder](https://github.com/wavemaker/docs/blob/themes/learn/app-development/ui-design/theme-builder.md). 
2. Updated Themes documentation for [Import and Apply theme](https://github.com/wavemaker/docs/blob/themes/learn/app-development/ui-design/themes.md).
3. Updated the structure for [Manually Creating a Theme](https://github.com/wavemaker/docs/blob/themes/learn/app-development/ui-design/creating-themes.md). 
4. Amended the side-nav to add [Theme Builder](https://github.com/wavemaker/docs/blob/themes/learn/app-development/ui-design/theme-builder.md) and moved [Themes](https://github.com/wavemaker/docs/blob/themes/learn/app-development/ui-design/themes.md) below template for **Styles** category. 
5. Added a **See Also** section for referencing the related documentation to include [Customizing Existing Theme](https://github.com/wavemaker/docs/blob/themes/learn/how-tos/customize-existing-theme.md), [Customizing Theme](https://github.com/wavemaker/docs/blob/themes/learn/how-tos/customizing-theme.md) and other three documents mentioned above.

**Comment by lovin26** [comment]
Why do we have Create template under Develop themes tree?

image

**Comment by lovin26** [comment]
> Can you include screenshots of the changes? @swethakundaram

Screenshots 
Under Styles- 
image

Under Develop Themes-
Screenshot 2020-06-10 at 11 15 06 AM
image

**Comment by swethakundaram** [comment]
@lovin26 considering themes and templates both could go hand-in-hand in terms of development bundles. If you have a recommendation, let me know where you want it to go. 

Otherwise, we can change the title **Develop Themes** to something else.

**Comment by lovin26** [comment]
@swethakundaram Yes, we can change the title for Develop themes. Also, I feel that "Styles" and "Develop themes" sections should be next to each other.  The list can go as:
Pages
- Page overview
- Creating a page
- Page configure
- Page actions
- Style
- Develop themes

**Comment by swethakundaram** [comment]
@lovin26, 
Right now
image
I think for the flow, it also contains layout and templates which users want to see as soon as they develop a page and not at the end. 

Proposed
image

**Pull request merged**
